# Model Constants

PATTERN_TYPE_IGNORE = 1
PATTERN_TYPE_SPAM = 2
PATTERN_TYPE_USER_SELECTED = 3
PATTERN_TYPE_ELECTION = 4


SENDER_TYPE_SMS   = 2
SENDER_TYPE_EMAIL = 3
SENDER_TYPE_VOICECALL   = 4

MESSAGE_STATUS_SUSPICIOUS = 1
MESSAGE_STATUS_SPAM = 2
MESSAGE_STATUS_IGNORE = 3
MESSAGE_STATUS_USER_SELECTED = 4
MESSAGE_STATUS_ELECTION = 5
MESSAGE_STATUS_USER_SELECTED_SPAM = 6
MESSAGE_STATUS_USER_SELECTED_IGNORE= 7









